spring:
  application:
    name: Template
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  cache:
    type: redis
    redis:
      time-to-live: 30m
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

server:
  servlet:
    context-path: /api

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1

minio:
  host: ${MINIO_HOST:localhost}
  port: ${MINIO_PORT:9000}
  secure: false
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET}

knife4j:
  enable: true
  production: false
  setting:
    swagger-model-name: 实体类列表

logging:
  level:
    com.dxmy: debug

app:
  auth:
    skip-auth-paths:
      - /open/**
  cache:
    time-to-live:
      user: 30m
      role: 30m
      permission: 30m
