# 数据库配置
MYSQL_DB: test

# Redis 配置
REDIS_HOST: 192.168.88.128
REDIS_PORT: 6879
REDIS_PASSWORD: Fs@020301

# RabbitMQ 配置
RABBITMQ_HOST: 192.168.88.128
RABBITMQ_PORT: 5678
RABBITMQ_USERNAME: dxmy
RABBITMQ_PASSWORD: Fs@020301

# MinIO 配置
MINIO_HOST: 192.168.88.128
MINIO_PORT: 9008
MINIO_ACCESS_KEY: dxmy
MINIO_SECRET_KEY: Fs@020301
MINIO_BUCKET: test
